export const TEMPLATES = [
  {
    id: 'modern',
    name: 'Современный',
    description: 'Чистый минималистичный дизайн',
    preview: 'bg-blue-500',
  },
  {
    id: 'elegant',
    name: 'Элегантный',
    description: 'Премиум стиль с тёмными акцентами',
    preview: 'bg-gray-900',
  },
  {
    id: 'bold',
    name: 'Яркий',
    description: 'Насыщенные цвета и крупные элементы',
    preview: 'bg-orange-500',
  },
  {
    id: 'minimal',
    name: 'Минимал',
    description: 'Белый фон, тонкие линии',
    preview: 'bg-white border',
  },
  {
    id: 'luxury',
    name: 'Люкс',
    description: 'Золото и тёмный фон',
    preview: 'bg-yellow-800',
  },
];

export const TEMPLATE_DEFAULTS = {
  modern: {
    primaryColor: '#2563eb',
    secondaryColor: '#1e40af',
    accentColor: '#f59e0b',
    backgroundColor: '#f1f5f9',
    cardBackground: '#ffffff',
    textColor: '#1e293b',
    mutedColor: '#64748b',
    borderRadius: 12,
  },
  elegant: {
    primaryColor: '#1e293b',
    secondaryColor: '#334155',
    accentColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    cardBackground: '#ffffff',
    textColor: '#0f172a',
    mutedColor: '#475569',
    borderRadius: 4,
  },
  bold: {
    primaryColor: '#ea580c',
    secondaryColor: '#dc2626',
    accentColor: '#fbbf24',
    backgroundColor: '#fff7ed',
    cardBackground: '#ffffff',
    textColor: '#1c1917',
    mutedColor: '#57534e',
    borderRadius: 16,
  },
  minimal: {
    primaryColor: '#18181b',
    secondaryColor: '#3f3f46',
    accentColor: '#6366f1',
    backgroundColor: '#ffffff',
    cardBackground: '#fafafa',
    textColor: '#18181b',
    mutedColor: '#71717a',
    borderRadius: 8,
  },
  luxury: {
    primaryColor: '#92400e',
    secondaryColor: '#78350f',
    accentColor: '#fcd34d',
    backgroundColor: '#1c1917',
    cardBackground: '#292524',
    textColor: '#fef3c7',
    mutedColor: '#d4b896',
    borderRadius: 4,
  },
};

export const GOOGLE_FONTS = [
  'Inter',
  'Roboto',
  'Open Sans',
  'Montserrat',
  'Lato',
  'Raleway',
  'Playfair Display',
  'Merriweather',
  'Oswald',
  'Nunito',
  'Poppins',
  'Source Sans Pro',
  'Ubuntu',
  'PT Serif',
  'Cormorant',
];
